/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings --include-runtime=false --strict-vars=false` (hash: be6759193a8c1fc0e87abc31ad07f735)
declare namespace Cloudflare {
  interface Env {}
}
interface CloudflareBindings extends Cloudflare.Env {}
